# Notebook for ranking Investors and Companies

In [1]:
import pandas as pd
import sys
import os
from sklearn.preprocessing import MinMaxScaler

In [2]:
clean_company = pd.read_csv('../data/cleaned/preprocessed_company_profile.csv')

In [3]:
clean_deals = pd.read_csv('../data/cleaned/preprocessed_deals.csv')

In [4]:
clean_investors = pd.read_csv('../data/cleaned/preprocessed_investors.csv')

In [5]:
# Get the absolute path of the scripts folder
scripts_path = os.path.abspath('../scripts')

# Add the scripts folder to the sys.path
sys.path.append(scripts_path)

In [6]:
company_and_deals = pd.read_csv('../data/cleaned/company_and_deals.csv')

In [7]:
from rank_investors import type_rank, exit_multiple
type_rank(clean_investors)
clean_investors.head()
exit_multiple(clean_investors)

In [8]:
clean_investors[clean_investors['Exit Multiple'] > 1].describe()

,Unnamed: 0,# of Investment Professionals,Year Founded,AUM,Total Investments,Total Exits,Age,Investor Type Rank,Exit Multiple
count,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000
mean,3032.905660,1.308176,1989.742138,385.914717,8.515723,11.264151,35.257862,6.226415,1.785767
std,1621.781732,2.659946,42.288523,2225.651788,14.400183,16.662492,42.288523,2.459609,0.865188
min,69.000000,0.000000,1801.000000,0.000000,1.000000,2.000000,-1.000000,0.000000,1.028571
25%,1698.500000,0.000000,1971.000000,0.000000,1.000000,3.000000,-1.000000,6.000000,1.250000
50%,2797.000000,0.000000,2001.000000,0.000000,3.000000,5.000000,24.000000,7.000000,1.500000
75%,4489.000000,2.000000,2026.000000,0.000000,8.500000,11.000000,54.000000,7.000000,2.000000
max,5915.000000,21.000000,2026.000000,20269.750000,83.000000,100.000000,224.000000,10.000000,7.000000

In [9]:
from rank_investors import quartile_ranking, investor_age_score
quartile_ranking(clean_investors)
investor_age_score(clean_investors)

In [10]:
from rank_investors import weighted_rank
weighted_rank(clean_investors)

In [11]:
clean_investors.sort_values(by='Weighted Investor Score', ascending=False)

,Unnamed: 0,Investor ID,Investors,Investor Legal Name,Description,Primary Investor Type,# of Investment Professionals,Year Founded,Website,AUM,...,Age,Investor Type Rank,Exit Multiple,# of Investment Professionals QRank,AUM QRank,Total Investments QRank,Total Exits QRank,Investor Age Score,Weighted Investor Score,Investor Score Final
93,93,11215-09,3i Group,3i Group plc,"Founded in 1945, 3i Group is a private equity ...",PE/Buyout,141.0,1945.0,www.3i.com,46167.25,...,80.0,10,0.628719,8.0,10.0,10.0,9.0,10,69.700515,100.000000
39,39,10150-21,Fortress Investment Group,"Fortress Investment Group, LLC","Founded in 1998, Fortress Investment Group is ...",PE/Buyout,76.0,1998.0,www.fortress.com,49000.00,...,27.0,10,0.511696,8.0,10.0,10.0,9.0,10,69.290936,99.381305
23,23,11105-47,Adams Street Partners,"Adams Street Partners, LLC","Founded in 1972, Adams Street Partners is a pr...",PE/Buyout,224.0,1972.0,www.adamsstreetpartners.com,62000.00,...,53.0,10,0.509479,8.0,10.0,10.0,9.0,10,69.283175,99.369583
77,77,11105-11,Actis,Actis Capital LLP,"Founded in 2004, Actis is a private equity fir...",PE/Buyout,116.0,2004.0,www.act.is,15100.00,...,21.0,10,0.591479,8.0,9.0,10.0,9.0,10,69.070175,99.047833
140,140,10015-12,Advent International,"Advent International, L.P.","Founded in 1984, Advent International is a pri...",PE/Buyout,284.0,1984.0,www.adventinternational.com,82519.28,...,41.0,10,0.441469,8.0,10.0,10.0,9.0,10,69.045142,99.010018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3579,3579,156669-85,Lois E. Hopkins Irrevocable Trust,Unknown,NaN,Other,0.0,2026.0,Unknown,0.00,...,-1.0,0,0.000000,0.0,0.0,0.0,1.0,2,3.500000,0.000000
5524,5524,481374-82,Triple Point Asset Management,"Triple Point Asset Management, LLC",NaN,Holding Company,0.0,2026.0,Unknown,0.00,...,-1.0,0,0.000000,0.0,0.0,0.0,1.0,2,3.500000,0.000000
3975,3975,148125-07,NavPart I,Unknown,NaN,Other,0.0,2026.0,Unknown,0.00,...,-1.0,0,0.000000,0.0,0.0,0.0,1.0,2,3.500000,0.000000
1406,1406,156670-21,Barone Family Trust,Unknown,NaN,Other,0.0,2026.0,Unknown,0.00,...,-1.0,0,0.000000,0.0,0.0,0.0,1.0,2,3.500000,0.000000
5886,5886,157377-97,Wright Family Partnership,Unknown,NaN,Other,0.0,2026.0,Unknown,0.00,...,-1.0,0,0.000000,0.0,0.0,0.0,1.0,2,3.500000,0.000000

In [12]:
clean_investors.describe()

,Unnamed: 0,# of Investment Professionals,Year Founded,AUM,Total Investments,Total Exits,Age,Investor Type Rank,Exit Multiple,# of Investment Professionals QRank,AUM QRank,Total Investments QRank,Total Exits QRank,Investor Age Score,Weighted Investor Score,Investor Score Final
count,5972.000000,5972.000000,5972.000000,5.972000e+03,5972.00000,5972.000000,5972.000000,5972.000000,5972.000000,5972.000000,5972.000000,5972.000000,5972.000000,5972.000000,5972.000000,5972.000000
mean,2985.500000,42.531815,1997.135800,1.916290e+04,120.34779,42.350804,27.864200,5.950770,0.488248,2.707468,1.706129,5.393168,4.294039,8.060784,38.687602,53.153064
std,1724.112235,2536.545895,31.596234,2.803171e+05,368.53975,93.977513,31.596234,2.636701,0.373419,2.690037,3.006364,2.954544,2.876154,3.089166,13.555451,20.476353
min,0.000000,0.000000,1801.000000,0.000000e+00,0.00000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,3.500000,0.000000
25%,1492.750000,0.000000,1991.000000,0.000000e+00,10.00000,3.000000,10.000000,6.000000,0.250000,0.000000,0.000000,3.000000,1.000000,8.000000,29.976998,39.995154
50%,2985.500000,3.000000,2003.000000,0.000000e+00,34.00000,15.000000,22.000000,6.000000,0.446281,2.000000,0.000000,5.000000,4.000000,10.000000,38.458042,52.806299
75%,4478.250000,6.000000,2015.000000,1.000000e+02,102.00000,43.000000,34.000000,7.000000,0.666667,5.000000,2.000000,8.000000,7.000000,10.000000,48.213584,67.542654
max,5971.000000,196000.000000,2026.000000,1.160000e+07,9903.00000,1862.000000,224.000000,10.000000,7.000000,8.000000,10.000000,10.000000,9.000000,10.000000,69.700515,100.000000

In [13]:
clean_investors.to_csv('../data/ranked/ranked_investors.csv')

In [14]:
clean_company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2123 entries, 0 to 2122
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                2123 non-null   int64
 1   Company ID                2123 non-null   object
 2   Companies                 2123 non-null   object
 3   Revenue                   2123 non-null   float64
 4   Business Status           2123 non-null   object
 5   Revenue Growth %          2123 non-null   float64
 6   Last Financing Size       2123 non-null   float64
 7   Website                   2123 non-null   object
 8   LinkedIn URL              2123 non-null   object
 9   Last Financing Valuation  2123 non-null   float64
 10  Total Patent Documents    2123 non-null   float64
 11  Active Patent Documents   2123 non-null   float64
 12  Acquirers                 2123 non-null   object
 13  Active Investors          2123 non-null   object
 14  Total Clinical Trials     2123 non-null   float64
 15  Year Founded              2123 non-null   float64
dtypes: float64(8), int64(1), object(7)
memory usage: 265.5+ KB

In [15]:
clean_company['Business Status'].unique()

array(['Profitable', 'Generating Revenue/Not Profitable',
       'Generating Revenue', 'Bankruptcy: Admin/Reorg',
       'Product Development', 'Unknown', 'Out of Business', 'Restart',
       'Bankruptcy: Liquidation', 'Startup', 'Clinical Trials - Phase 2',
       'Clinical Trials - Phase 1', 'Clinical Trials - General',
       'Product In Beta Test', 'Stealth'], dtype=object)

In [16]:
from rank_company import status_rank, age_score
status_rank(clean_company)
age_score(clean_company)

In [17]:
clean_company

,Unnamed: 0,Company ID,Companies,Revenue,Business Status,Revenue Growth %,Last Financing Size,Website,LinkedIn URL,Last Financing Valuation,Total Patent Documents,Active Patent Documents,Acquirers,Active Investors,Total Clinical Trials,Year Founded,Business Status Rank,Age,Age Score
0,0,10831-42,McKesson (NYS: MCK),359051.00,Profitable,16.22,2000.00,www.mckesson.com,http://www.linkedin.com/company/mckesson,0.00,388.0,177.0,Unknown,Unknown,0.0,1832.0,10,193.0,4
1,1,52120-00,Tencent Holdings (HKG: 00700),92015.98,Profitable,8.41,4150.00,www.tencent.com,http://www.linkedin.com/company/tencentglobal,0.00,23859.0,16013.0,Unknown,"DST Global, Hillhouse Investment Group, Knicke...",0.0,1998.0,10,27.0,4
2,2,10612-54,AstraZeneca (LON: AZN),54982.00,Profitable,15.48,5000.00,www.astrazeneca.com,http://www.linkedin.com/company/astrazeneca,0.00,29857.0,7710.0,Unknown,Unknown,4530.0,1913.0,10,112.0,4
3,3,10592-11,HP (NYS: HPQ),53878.00,Profitable,1.46,1000.00,www.hp.com,http://www.linkedin.com/company/hp,0.00,38063.0,12014.0,Unknown,Berkshire Hathaway,1.0,1939.0,10,86.0,4
4,4,10035-64,Intel (NAS: INTC),53044.00,Generating Revenue/Not Profitable,-3.97,5000.00,www.intel.com,http://www.linkedin.com/company/intel-corporation,0.00,161897.0,84745.0,Unknown,Unknown,10.0,1968.0,9,57.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2118,2142,56685-16,Zemblaz,0.00,Profitable,0.00,43.40,www.porthus.com,Unknown,43.40,0.0,0.0,Descartes Systems Group,Unknown,0.0,1999.0,10,26.0,4
2119,2143,51774-31,Zencoder ( Multimedia and Design Software),0.00,Generating Revenue,0.00,27.40,www.zencoder.com,http://www.linkedin.com/company/zencoder,27.40,0.0,0.0,Brightcove,Unknown,0.0,2007.0,8,18.0,4
2120,2145,54257-05,Zestra,0.00,Generating Revenue,0.00,0.00,www.zestra.com,http://www.linkedin.com/company/zestra,0.00,12.0,5.0,Innovus Pharmaceuticals,Unknown,0.0,1996.0,8,29.0,4
2121,2146,14767-66,Zonare Medical Systems,0.00,Generating Revenue,0.00,105.00,www.zonare.com,http://www.linkedin.com/company/zonare-medical...,105.00,27.0,8.0,Mindray,Unknown,0.0,1999.0,8,26.0,4
2122,2147,120584-17,Zpredicta,0.00,Generating Revenue,0.00,9.59,www.zpredicta.com,Unknown,9.59,9.0,4.0,Predictive Oncology,Unknown,0.0,2014.0,8,11.0,10

In [18]:
from rank_company import quartile_ranking
quartile_ranking(clean_company)

In [19]:
clean_company

,Unnamed: 0,Company ID,Companies,Revenue,Business Status,Revenue Growth %,Last Financing Size,Website,LinkedIn URL,Last Financing Valuation,...,Business Status Rank,Age,Age Score,Revenue QRank,Revenue Growth % QRank,Last Financing Size QRank,Last Financing Valuation QRank,Total Patent Documents QRank,Active Patent Documents QRank,Total Clinical Trials QRank
0,0,10831-42,McKesson (NYS: MCK),359051.00,Profitable,16.22,2000.00,www.mckesson.com,http://www.linkedin.com/company/mckesson,0.00,...,10,193.0,4,10.0,6.0,10.0,0.0,8.0,8.0,0.0
1,1,52120-00,Tencent Holdings (HKG: 00700),92015.98,Profitable,8.41,4150.00,www.tencent.com,http://www.linkedin.com/company/tencentglobal,0.00,...,10,27.0,4,10.0,3.0,10.0,0.0,9.0,9.0,0.0
2,2,10612-54,AstraZeneca (LON: AZN),54982.00,Profitable,15.48,5000.00,www.astrazeneca.com,http://www.linkedin.com/company/astrazeneca,0.00,...,10,112.0,4,10.0,6.0,10.0,0.0,9.0,9.0,7.0
3,3,10592-11,HP (NYS: HPQ),53878.00,Profitable,1.46,1000.00,www.hp.com,http://www.linkedin.com/company/hp,0.00,...,10,86.0,4,10.0,1.0,9.0,0.0,9.0,9.0,1.0
4,4,10035-64,Intel (NAS: INTC),53044.00,Generating Revenue/Not Profitable,-3.97,5000.00,www.intel.com,http://www.linkedin.com/company/intel-corporation,0.00,...,9,57.0,4,10.0,0.0,10.0,0.0,9.0,9.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2118,2142,56685-16,Zemblaz,0.00,Profitable,0.00,43.40,www.porthus.com,Unknown,43.40,...,10,26.0,4,0.0,0.0,5.0,5.0,0.0,0.0,0.0
2119,2143,51774-31,Zencoder ( Multimedia and Design Software),0.00,Generating Revenue,0.00,27.40,www.zencoder.com,http://www.linkedin.com/company/zencoder,27.40,...,8,18.0,4,0.0,0.0,4.0,4.0,0.0,0.0,0.0
2120,2145,54257-05,Zestra,0.00,Generating Revenue,0.00,0.00,www.zestra.com,http://www.linkedin.com/company/zestra,0.00,...,8,29.0,4,0.0,0.0,0.0,0.0,4.0,3.0,0.0
2121,2146,14767-66,Zonare Medical Systems,0.00,Generating Revenue,0.00,105.00,www.zonare.com,http://www.linkedin.com/company/zonare-medical...,105.00,...,8,26.0,4,0.0,0.0,7.0,7.0,5.0,4.0,0.0
2122,2147,120584-17,Zpredicta,0.00,Generating Revenue,0.00,9.59,www.zpredicta.com,Unknown,9.59,...,8,11.0,10,0.0,0.0,2.0,2.0,3.0,2.0,0.0

In [20]:
from rank_company import weighted_company_score
weighted_company_score(clean_company)
clean_company

,Unnamed: 0,Company ID,Companies,Revenue,Business Status,Revenue Growth %,Last Financing Size,Website,LinkedIn URL,Last Financing Valuation,...,Age Score,Revenue QRank,Revenue Growth % QRank,Last Financing Size QRank,Last Financing Valuation QRank,Total Patent Documents QRank,Active Patent Documents QRank,Total Clinical Trials QRank,Weighted Company Score,Company Score
0,0,10831-42,McKesson (NYS: MCK),359051.00,Profitable,16.22,2000.00,www.mckesson.com,http://www.linkedin.com/company/mckesson,0.00,...,4,10.0,6.0,10.0,0.0,8.0,8.0,0.0,114.0,71.661238
1,1,52120-00,Tencent Holdings (HKG: 00700),92015.98,Profitable,8.41,4150.00,www.tencent.com,http://www.linkedin.com/company/tencentglobal,0.00,...,4,10.0,3.0,10.0,0.0,9.0,9.0,0.0,111.5,70.032573
2,2,10612-54,AstraZeneca (LON: AZN),54982.00,Profitable,15.48,5000.00,www.astrazeneca.com,http://www.linkedin.com/company/astrazeneca,0.00,...,4,10.0,6.0,10.0,0.0,9.0,9.0,7.0,137.0,86.644951
3,3,10592-11,HP (NYS: HPQ),53878.00,Profitable,1.46,1000.00,www.hp.com,http://www.linkedin.com/company/hp,0.00,...,4,10.0,1.0,9.0,0.0,9.0,9.0,1.0,109.5,68.729642
4,4,10035-64,Intel (NAS: INTC),53044.00,Generating Revenue/Not Profitable,-3.97,5000.00,www.intel.com,http://www.linkedin.com/company/intel-corporation,0.00,...,4,10.0,0.0,10.0,0.0,9.0,9.0,5.0,118.5,74.592834
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2118,2142,56685-16,Zemblaz,0.00,Profitable,0.00,43.40,www.porthus.com,Unknown,43.40,...,4,0.0,0.0,5.0,5.0,0.0,0.0,0.0,61.5,37.459283
2119,2143,51774-31,Zencoder ( Multimedia and Design Software),0.00,Generating Revenue,0.00,27.40,www.zencoder.com,http://www.linkedin.com/company/zencoder,27.40,...,4,0.0,0.0,4.0,4.0,0.0,0.0,0.0,50.0,29.967427
2120,2145,54257-05,Zestra,0.00,Generating Revenue,0.00,0.00,www.zestra.com,http://www.linkedin.com/company/zestra,0.00,...,4,0.0,0.0,0.0,0.0,4.0,3.0,0.0,39.5,23.127036
2121,2146,14767-66,Zonare Medical Systems,0.00,Generating Revenue,0.00,105.00,www.zonare.com,http://www.linkedin.com/company/zonare-medical...,105.00,...,4,0.0,0.0,7.0,7.0,5.0,4.0,0.0,73.0,44.951140
2122,2147,120584-17,Zpredicta,0.00,Generating Revenue,0.00,9.59,www.zpredicta.com,Unknown,9.59,...,10,0.0,0.0,2.0,2.0,3.0,2.0,0.0,52.5,31.596091

In [21]:
clean_company.sort_values(by='Company Score', ascending=False)

,Unnamed: 0,Company ID,Companies,Revenue,Business Status,Revenue Growth %,Last Financing Size,Website,LinkedIn URL,Last Financing Valuation,...,Age Score,Revenue QRank,Revenue Growth % QRank,Last Financing Size QRank,Last Financing Valuation QRank,Total Patent Documents QRank,Active Patent Documents QRank,Total Clinical Trials QRank,Weighted Company Score,Company Score
44,44,12618-46,C. R. Bard,3875.40,Profitable,7.12,24000.00,www.crbard.com,Unknown,24000.00,...,4,10.0,3.0,10.0,10.0,9.0,9.0,7.0,157.5,100.000000
305,305,41941-72,Antares Pharma,183.46,Profitable,15.67,1045.67,www.antarespharma.com,http://www.linkedin.com/company/antares-pharma...,1045.67,...,4,8.0,6.0,10.0,10.0,9.0,8.0,5.0,149.5,94.788274
387,387,60580-27,Juno Therapeutics,111.87,Generating Revenue,40.97,10400.00,www.junotherapeutics.com,Unknown,11517.17,...,10,7.0,8.0,10.0,10.0,9.0,8.0,5.0,148.5,94.136808
94,94,25334-56,Welch Allyn,1426.40,Generating Revenue,56.45,1686.80,www.welchallyn.com,Unknown,1686.80,...,4,10.0,9.0,10.0,10.0,9.0,9.0,3.0,147.5,93.485342
242,242,40641-85,K2M,280.62,Profitable,11.35,1380.00,www.k2m.com,Unknown,1380.00,...,4,8.0,4.0,10.0,10.0,9.0,9.0,5.0,147.0,93.159609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020,2042,646489-09,Tiw Corporation,0.00,Unknown,0.00,0.00,tiwtools.com,http://www.linkedin.com/company/tiw-corporation,0.00,...,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.000000
1811,1829,535016-62,Pointer (Software Development Applications),0.00,Out of Business,0.00,0.00,www.pointer.gg,Unknown,0.00,...,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.000000
2014,2036,510839-65,Thomson Reuters Tax & Accounting (Web Builder ...,0.00,Unknown,0.00,0.00,Unknown,Unknown,0.00,...,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.000000
2050,2072,64937-89,Upside Financial,0.00,Out of Business,0.00,0.00,www.upsideadvisor.com,Unknown,0.00,...,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.000000
2090,2113,647400-61,web904.com,0.00,Unknown,0.00,0.00,web904.com,http://www.linkedin.com/company/web904.com-llc,0.00,...,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.000000

In [22]:
clean_company.to_csv('../data/ranked/ranked_companies.csv')